### ISSUE TITLE
Data input in it got lost for no reason?

### ISSUE THREAD

**Issue by mgracer48** [Slimmmo/Slimmmo.github.io#101]
This is espically annoying on ios because u cant import the capitalist save file

**Comment by 61352151511** [comment]
It's saved as cookies, so if the cookies were somehow cleared then that's why everything has gone missing. I'm not sure about why you can't import a save file on iOS. If you mean actually importing the games current state, no you can't currently do that on any platform. However you can save the calculators state to a txt file and import that, if you mean that doesn't work then I do not know why, I don't use iOS so I can't test but I know it works on android.

**Comment by mgracer48** [comment]
Yea but i never deleted any cookies

**Comment by 61352151511** [comment]
That's odd then. There's really nothing that can be done. You should still be able to export the calculator save state and load the file whenever just incase something like this were to happen again. Something I would like to see eventually added to the calculator is "Signing in" with Google or twitter in order to be able to have the calculator save to that and then you can access it from any PC, however I have no idea if this is possible or how it could be done.

**Comment by mgracer48** [comment]
This needs to happen espically for ios users

**Comment by Slimmmo** [comment]
One thing I've noticed is that there is a different set of cookies for
http://sli ... and https://sli ... so maybe that is your issue? You might
be using the https version when your cookies are saved on the http version
or vice versa?
