### ISSUE TITLE
Earth heavily changed again

### ISSUE THREAD

**Issue by alexmaurizio** [Slimmmo/Slimmmo.github.io#139]
Just an heads up: Earth was changed in it's upgrade progress and now has numerous paywalls under the form of "permanent megabucks updates".

This removes the ability to buy some of those upgrades in specific (long) wait sessions, so it's now hitting time walls that you can only jump by waiting a LOT or by getting megabucks.

I think we need a new accordion for those "Megabucks Upgrades" now

Also on a side note (not affecting the calculator), the Megabucks ratio on Moon got extremely fucked up so it's now 10 times bigger (at least).

I'd need some serious math confirmation for this but here's a proof, this was the $1 Unnonagintillion Angel Investor 5 which is now not available to purchase anymore without spending cash

![Paywalls](https://user-images.githubusercontent.com/15074818/34035353-17e867e6-e182-11e7-8964-2953d724752c.png)

**Comment by Daimona** [comment]
I confirm what has been said above (though I don't know about the moon). This new upgrade is actually evil for several reasons: 
1-Many old upgrades are now MB upgrades, making it harder to buy new ones; about this, the first one I noticed is the 4.4444..x one, and around the quattuorsexagintillion upgrades now almost half of 'em is in MB. 
2-Why the fuck MB upgrades should be in the cash upgrades section? We have one for angel upgrades, they could have added one for MB ones. 
3-Upgrades are seriously unbalanced: they're really not worth it, e.g. a single Mega Ticket costs much less and gives much more. 
And finally, 4, since those upgrades are mixed up it's actually really easy to misclick one of them, especially when buying stacks of upgrades all together. Of course no confirm is asked and for a wrong click I suddenly found myself with 15 MB instead of 80, which really turned me mad. 
Moreover, some upgrades have been resized. I can only provide one of them, which is the 1 Octoquinquagintillion upgrade. It used to be a 9x, now it's 1.8x and I suppose it's not the only one. 
I suspect that the calculator isn't maintained anymore, but I have some knowledge in javascript, so I'd be glad to help. However I can't do it on my own, mainly 'cause it would take too much time.
Let me know, thanks in advance.
P.S. As a personal note, it sounds like devs have become much greedier for gold, which might turn players greedier for cheats.

**Comment by Nutty69** [comment]
I'm having fun delving into the code for this calculator and would be happy to try to help out; however, (a) I'm new to GitHub and don't quite understand all the intricacies of forking and cloning and collaborating and (b) I am not a programmer, but do have a CompSci background.

I've reached out to HyperHippo to (a) ask if they would consider putting Mega Bucks upgrades on their own tab or at least increasing the number of upgrades visible at a time and (b) to see if they will provide the full list of Mega Bucks upgrades with their costs and benefits since I accidentally mis-clicked at least one Mega Buck upgrade and thus can't recreate the full list on my own (with my next restart in a couple of days, I can figure out which Mega Bucks upgrades I accidentally bought but not how much they cost me).

Issues I see right off the bat:
1) Mega Bucks upgrades are tossed into the list of cash upgrades in game making it impossible to purchase cash upgrades "out of order" once you can see "too many" of the MB upgrades. Would the calculator need to account for that? How?
2) Would it be good to have an entry in the "Recommendation Filters" for "Don't show Mega Bucks upgrades".

And issues crop up with which MB upgrades are visible to the player. On my run, I think was able to see all of the MB upgrades I had "unlocked" by getting to cash upgrades beyond them until I switched planets and came back to Earth. Now I can only see the first 11 MB upgrades that I haven't purchased;
I can see none of the MB upgrades beyond those even though I've theoretically "unlocked" the ones through $1 Nonagintillion; and I can see none of the cash upgrades I am able to purchase.

![image](https://user-images.githubusercontent.com/36167561/35936227-7dc6bfd2-0bf7-11e8-9e3d-2ef3fd6f088b.png)

Those MB upgrades correspond to the Angel Investor upgrades that used to cost from $1 Quattuorseptuagintillion through $1 Quattuoroctogintillion (inclusive); but I think I was able to see the ones that would go through what used to be available at $1 Nonagintillion until switching planets.

Thoughts on how to proceed? I'm going to play in my clone later and see what I can figure out about what's going on where and why to see what I think would need to happen and how.

**Comment by Nutty69** [comment]
I've cloned? forked? this repo to my own github so I can play around with the Mega Bucks Upgrades a little (https://nutty69.github.io) if you want to check it out.

So far, I've only dealt with the visual aspect of putting Mega Bucks Upgrades into their own accordion and I don't *think* I've broken anything :-)

I removed the upgrades that I can confirm cost Mega Bucks from `earth.cashUpgrades[]` and created  `earth.megabucksUpgrades[]` with them. Things are displaying appropriately, I think.

To do:
* - [ ] Add toggle whether to include MB Upgrade recommendations (similar to "Don't show +1 / +10 / +100")
* Deal with
  * - [ ] Saving
  * - [ ] Loading
  * - [ ] resetPlanet()
  * - [ ] fullyResetPlanet() 
  * - [ ] Make calculations look at MB upgrades for recommendations (if not toggled off) but make sure it doesn't look at ones that the user can't see (how can this be determined?)
  * - [ ] Figure out how to display MB cost in recommendation list (I'm using "MB$" in the "Mega Bucks Upgrades" accordion)
  * - [ ] Make calculator show upgrades beyond MB upgrades in order of cost not order of benefit since they can't be bought out of sequence
  * - [ ] Probably a lot of other stuff as well

As I'm writing this, I wonder if Mega Bucks Upgrades should be dealt with similarly to Super Badges and Suits -- i.e. not displayed in recommendations list, but have the "+" icons for the most helpful.... Except, of course, they're all helpful with the higher effectiveness boosts being better. One issue is how to determine which ones the player has access to so as not to highlight a Mega Bucks Upgrade the player can't see in game.

Thoughts on any of this?

**Comment by Slimmmo** [comment]
Since you can get so many megabucks for free I don't think it's worth comparing them to $ upgrades.

Ranking the MB upgrades between each-other is worth doing but if we don't know which ones the user can/can't see we'll probably have to just rank them all in order and let the user find the best one they have.

**Comment by Jemsterr** [comment]
Also changed: Earth $1 Octillion Lemon upgrade  through to Oil Profit at $50 nonillian are all x3 upgrades and not x7 as in the table, and there is a "everything x2.33" added for 35 MB just before the $1 tredecillion "All Profits x7" cash upgrade.

**Comment by Nutty69** [comment]
@Jemsterr, that would explain why my Steam game's in-game numbers match the calculator; apparently I accidentally bought that x2.33 MB upgrade and it (effectively) makes those x3s into x7s once purchased.

Do you know of any other changes below $1 quattuorseptuagintillion? (I'm going to restart earth on Steam tomorrow and can check myself, but I think I accidentally bought at least one other MB upgrade and don't know the cost.)

**Comment by Nutty69** [comment]
I just restarted Earth on Steam and was able to compare the available upgrades against the calculator. I've made two lists....The first is everything I can confirm is changed in Steam versus the calculator. The second is a list of upgrades that are in the calculator but are not in my Steam game. I suspect that they may have been turned into MB upgrades.

I don't know if there are any changes beyond the "Angel Investor 5" (at what was the $1 quattuornonagintillion level) because that's as far ahead as I can see in the upgrades list.

@Daimona or @Jemsterr (or anyone else, really): do you have a list of MB upgrades below what used to cost $1 quattuorseptuagintillion?

Verified changes in Steam as compared to the calculator:

What | Price Level | Change
-----|------|-------
Lemon Profit 7 | ($1 Octillion) | Now x3
Carwash Profit 7 | ($25 Octillion) | Now x3
Pizza Profit 7 | ($100 Octillion) | Now x3
Donut Profit 7 | ($250 Octillion) | Now x3
Shrimp Profit 7 | ($500 Octillion) | Now x3
Hockey Profit 7 | ($1 Nonillion) | Now x3
Movies Profit 7 | ($5 Nonillion) | Now x3
Bank Profit 7 | ($25 Nonillion) | Now x3
Oil Profit 7 | ($50 Nonillion) | Now x3
All Profit 9 | ($1 Octoquinquagintillion) | Now x1.8
Angel Investor 2 | ($1 Quattuorseptuagintillion) | Now MB$200
Angel Investor 1.2 | ($1 Quinseptuagintillion) | Now MB$200
Angel Investor 1.3 | ($1 Sexseptuagintillion) | Now MB$200
Angel Investor 0.7 | ($10 Sexseptuagintillion) | Now MB$200
Angel Investor 2 | ($1 Octoseptuagintillion) | Now MB$200
Angel Investor 0.3 | ($1 Novemseptuagintillion) | Now MB$200
Angel Investor 1 | ($1 Octogintillion) | Now MB$200
Angel Investor 1.5 | ($1 Unoctogintillion) | Now MB$200
Angel Investor 0.9 | ($1 Duooctogintillion) | Now MB$200
Angel Investor 0.6 | ($1 Treoctogintillion) | Now MB$200
Angel Investor 1 | ($1 Quattuoroctogintillion) | Now MB$200
Angel Investor 1.1 | ($1 Quinoctogintillion) | Now MB$200
Angel Investor 0.9 | ($1 Sexoctogintillion) | Now MB$200
Angel Investor 2 | ($1 Septoctogintillion) | Now MB$200
Angel Investor 3 | ($1 Octooctogintillion) | Now MB$200
Angel Investor 4 | ($1 Novemoctogintillion) | Now MB$200
Angel Investor 1 | ($1 Nonagintillion) | Now MB$200
Angel Investor 5 | ($1 Unnonagintillion) | Now MB$200
Angel Investor 2.1 | ($1 Duononagintillion) | Now MB$200
Angel Investor 4 | ($1 Trenonagintillion) | Now MB$200
Angel Investor 5 | ($1 Quattuornonagintillion) | Now MB$200

Missing entries in my Steam game (likely converted to MB upgrades that I purchased)

What | Price Level
-----|-----
Movies Profit 3 | ($7 Quadrillion)
Donut Profit 3 | ($20 Quintillion)
Newspaper Profit 7 | ($5 Octillion)
All Profit 3 | ($450 Septentrigintillion)
All Profit 4.44444444444 | ($500 Quinquagintillion)
All Profit 5 | ($2 Quinsexagintillion)
Lemon Profit 3 | ($1 Sexsexagintillion)
Carwash Profit 3 | ($96 Sexsexagintillion)
Shrimp Profit 3 | ($679 Sexsexagintillion)
Bank Profit 3 | ($81 Septsexagintillion)
Angel Investor 2.1 | ($1 Octosexagintillion)
Hockey Profit 3 | ($9 Octosexagintillion)
Oil Profit 3 | ($328 Octosexagintillion)
Angel Investor 1.5 | ($1 Septuagintillion)
Angel Investor 1 | ($1 Unseptuagintillion)
Angel Investor 2 | ($1 Duoseptuagintillion)
Angel Investor 0.5 | ($1 Treseptuagintillion)

**Comment by Nutty69** [comment]
Per Michael at HyperHippo:

> All the Upgrades should cost the same across each platform. We actually don't have a complete list of all the Mega Bucks upgrades available, but I can let you know that there are quite a few of them! 

Michael suggested checking the [AdCap Wikia](http://adventure-capitalist.wikia.com/wiki/AdVenture_Capitalist_Wiki), but that list doesn't have the MB upgrades.

**Comment by Jemsterr** [comment]
Movie Profit 3 (was $7 quadrillion) now 5MB

**Comment by Nutty69** [comment]
@Jemsterr, thanks. I've updated the list with that info and more based on reddit posts I found that included screenshots.

Now all that's missing are Donut Profit 3 (was $20 quintillion) and Newspaper Profit 7 (was $5 octillion). Once I have those, I can play around some more on my copy.

**Comment by Nutty69** [comment]
In addition to not having a way to figure out which MB upgrades a player can see, there appears to be no easy way for the player to know which MB s/he has already purchased. Once bought, MB upgrades disappear from the list.

Users will have to compare in-game vs calculator numbers for angel effectiveness and choose MB upgrades to make up the difference, recalculate, and then compare per investment profit-per-second and choose MB upgrades there as well (fortunately, there appear to be only one MB upgrade per investment).

**Comment by Nutty69** [comment]
I received a PM from a reddit user with info on "Bacon Sprinkles" and "Celebrity Delivery" so now I can play around a little -- the only caveat is that I can't see far enough into the upgrade list to know whether any of the final three (as of now) upgrades ("Drill Oil Personally", "Live Rich", and "And Profit!") cost Mega Bucks or if they remain as cash upgrades.

I'm toying with two ideas on how to handle recommendations for MB upgrades:
* Use "+" signs similar to Super Badges and Suits (although it would have to allow selections to be non-exclusive)
* Create a separate "MB Recommendations" table

I'm happy to entertain other ideas.

**Comment by Nutty69** [comment]
I just ran through the MB upgrades and found the following tidbits:
* It will take MB$6080 to buy them all:
  * It costs MB$275 and $1 Octoquinquaginitillion to restore the "All Profit" and some investment profit boosts to pre-Mega Bucks levels
  * It costs MB$605 to restore one x3 profit boost for each investment except Pizza (which lost no boosts to Mega Bucks)
  * In costs MB$5200 to restore the +47.7% Angel Investor Effectiveness to pre-Mega Bucks levels

**Comment by Nutty69** [comment]
I've done some work on incorporating the Mega Bucks Upgrades over in [my version](https://nutty69.github.io) of this repo.

At this point, I'm using the plus-sign-styling (including purple for the "best" choice) rather than creating a separate recommendations table.

The table of upgrades is in the same order as the upgrades become available in game.

The code is not complete as I still need to work on:
- [ ] Why doesn't plus sign disappear when item is checked
- [ ] Save and load Mega Bucks Upgrades

Please feel free to take a look at what's been implemented and provide feedback.

**Comment by Nutty69** [comment]
As of version 6.2, this is no longer an issue. Upgrades that had cost Earth Bucks, then Mega Bucks, once again cost Earth Bucks.
