### ISSUE TITLE
feature request: filter recommendations by % increase?

### ISSUE THREAD

**Issue by cwitty** [Slimmmo/Slimmmo.github.io#17]
How about an additional option in the "Filter recommendations" section, to ignore all recommendations with a "% increase" of less than a user-configurable amount?

**Comment by Slimmmo** [comment]
Sure. Will add it when I get some time.

**Comment by Slimmmo** [comment]
Feel free to re-open this if the current implementation has bugs.

**Comment by Dansiman** [comment]
Would like to see this accept values smaller than 1%. Currently, if the value in the % field is not an integer, the recommendations list becomes empty upon calculation. This is especially relevant on the Moon, because at a certain point anything other than an Oxygen or All multiplier is always going to be less than 1%, and often even less than .1%
