### ISSUE TITLE
Bug in Angel Upgrade

### ISSUE THREAD

**Issue by BaesFr** [Slimmmo/Slimmmo.github.io#52]
Hi Slimmmo,

I notice a problem in angel upgrades.

In the picture, you notice, I should buy the 2 green + on the 2nd column.

But I can't since it only display 15 items (the first one) and these 2 are after the 15 first items.

So in that case, I think you should recommand buying the 2-3-4 (?) not-so-bad items to show the item you recommand.

I hope that I'm clear enough

![image](https://cloud.githubusercontent.com/assets/2757528/14892801/d32e9f66-0d6c-11e6-914c-0de949f3b3f0.png)

**Comment by 61352151511** [comment]
If you have over 10 decillion angels (Which you do since it's recommending you buy these) You should be spending the million on the +10/+50 investments. These angel upgrades do not increase the cost of the investment. Spending 101ish billion angels is nothing compared to the decillions you have. Then you'll be able to buy the all profit x15

**Comment by jaysoncopes** [comment]
The way these calculations are made is by comparing your current
income/second compared to the income/second in the potential world with
that angel upgrade. If there is in increase in income, it will suggest it.
I guess maybe your questions simply isn't clear, but there doesn't seem to
be anything wrong with the suggestions.
On Thu, Apr 28, 2016 at 11:21 AM Mitchell <notifications@github.com> wrote:

> If you have over 10 decillion angels (Which you do since it's recommending
> you buy these) You should be spending the million on the +10/+50
> investments. These angel upgrades do not increase the cost of the
> investment. Spending 101ish billion angels is nothing compared to the
> decillions you have. Then you'll be able to buy the all profit x15
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Slimmmo/Slimmmo.github.io/issues/52#issuecomment-215483237>
>
-- 


~Alex A. Arze~

**Comment by BaesFr** [comment]
Ok, I understand. So in fact, the question was "Can you tell me what should I buy before buying the green one (the recommanded one) ?" and the answer is "the first item in the list (cheapest) until you reach what I have suggested you".

So it's not a bug, (the green plus is the best to buy) but if you can't buy it, buy something else until you can buy it.

In this case, buy the first one until you reach the green plus (so all the +10/+50).

Thanks to all for your answers.

I close this issue

**Comment by Dansiman** [comment]
Actually, BaesFr, you should buy **all** of the +10, +50, and +75 upgrades, and you should buy them at the very beginning after every reset from now on as well.

If you, for example, buy the +10, +50, and +75 Newspaper upgrades right after a reset, you'll have 135 Newspapers, but you'll also find that buying number 136 still costs $60, not $9.383 Billion, as it would if you had purchased those 135 Newspapers normally. So when those upgrades cost a very tiny percentage of your angels, you should definitely get them.

The reason they aren't highlighted in the calculator is simply because checking the box in the calculator doesn't also automatically add the quantity to your current numbers (probably because if it did, then it would be annoying when you're filling out a blank calculator, you enter all your business quantities, then all your upgrades, and suddenly see that your business quantities increased).
