### ISSUE TITLE
Earth math is broken

### ISSUE THREAD

**Issue by SummitSummit** [Slimmmo/Slimmmo.github.io#76]
I have 9200 Lemons.  Calculator says lemon 9201 costs $138.167 Octooctogintillion.  Game says lemon 9201 costs $1.243 Septoctogintillion.  
The same goes for everything else.

**Comment by dr-ishmael** [comment]
I'm thinking this is the same as issue #70 - please read my response there, basically: double-check all your upgrades and managers in the calculator.

**Comment by SummitSummit** [comment]
Double checked, triple checked.  I have all Angel purchases before the +25 Newspapers that cost 1 Duoquadragintillion Angels and they are checked accordingly.  I have Platinum Bonus x777.77, and it is checked.  I am wearing the White Suit, it is checked.  I have Total multiplier of x12 plugged in, and 0 Flux Capitalors.  
I did buy the micromanager (total waste of gold) that doesn't affect the cost of stuff, does it?

**Comment by dr-ishmael** [comment]
You didn't mention managers, and I'm pretty sure that's what you're missing, because it's exactly the difference. If I input 9200 Lemons, check off the Angel Upgrades up to 1 duoqadra, and *don't* check off the managers, it says $139.167 octoocto. But when I *do* check off the managers, it says $1.244 septocto, which matches the game (within the margin of error introduced by JS floating-point math).

**Comment by SummitSummit** [comment]
Aah, there it is.  That's got it.  I totally missed that one.  Haven't had to look at the managers thing in ages and I never got them all checked after the last cookie cleanse.  Thanks!  
As a side note, while checking everything I just found out about these Super Badges.  I don't have the one for Pizza, so Unicorn it is!
